version: '3.8'

services:
  # Kontener 1: Twoja Aplikacja
  app:
    build: .
    container_name: demo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/testdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  # Kontener 2: Baza danych (MySQL)
  db:
    image: mysql:8.0
    container_name: demo-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    ports:
      - "3306:3306"
